DATALOADER:
  batch_size: 8
  num_workers: 0
EXP:
  DATASET: modelnet40_pn2
  EXP_ID: pointnet2_pointnet2_run_mixup
  LOSS_NAME: cross_entropy
  MODEL_NAME: pointnet2
  SEED: 1
  TASK: cls
TRAIN:
  l2: 0.0